apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-registration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-registration-api
  template:
    metadata:
      labels:
        app: device-registration-api
    spec:
      containers:
      - name: device-registration-api
        image: dbnmrs/devregapi:latest
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-minikube-postgresql
                key: postgres-password
          - name: POSTGRES_DB
            value: "jsafraapi"
          - name: POSTGRES_HOST
            value: "pg-minikube-postgresql"
          - name: POSTGRES_PORT
            value: "5432"
