apiVersion: v1
kind: Service
metadata:
  name: device-registration-api-service
spec:
  selector:
    app: device-registration-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
